# 环境配置

1.打开Anaconda3 Prompt，创建环境并指定python版本

```python
conda create -n tf-new python=3.7
```

2.激活环境

```
activate tf-new
```

3.安装tensorflow

```python
conda install tensorflow==1.15.0
```

此时会出现安装不成功的情况，并提供anaconda.org的地址，进入此网站检索tensorflow选择合适版本并复制指令即可。需要注意的是，不同tensorflow版本对应的Python版本不同，需要安装对应版本。

4.安装验证

```python
import tensorflow as tf 
sess = tf.Session() 
a = tf.constant(1) 
b = tf.constant(2) 
print(sess.run(a+b)) 
```

5.在pycharm中配置环境

### 报错：

```python
2022-12-10 16:43:15.724061: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
```

原因：你的CPU支持AVX扩展，但是你安装的TensorFlow版本无法编译使用。

解决方法：在代码中加入如下代码，忽略警告：

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```

### 报错：

```python
Traceback (most recent call last):
  File "D:/tensorflow-new/main.py", line 70, in <module>
    tf.app.run()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "D:/tensorflow-new/main.py", line 54, in main
    env = GymEnvironment(config)
  File "D:\tensorflow-new\dqn\environment.py", line 68, in __init__
    super(GymEnvironment, self).__init__(config)
  File "D:\tensorflow-new\dqn\environment.py", line 9, in __init__
    self.env = gym.make(Breakout - v)
NameError: name 'Breakout' is not defined
```

解决方法：

```python
conda install ale-py
conda install gym[accept-rom-license]
```

此时默认安装ale-py 0.8.0版本，由于此版本不支持Python3.7版本，应选用其他版本的ale-py源，方法有两种：

1.在设置中手动添加ale-py包，在install前选择特定版本（本机无其余版本可选）

2.自行安装其它版本ale-py。在[Python库|ale_py-0.7rc2-cp38-cp38-macosx_10_15_x86_64.whl_安装ale-py的版本为0.7.2-Python文档类资源-CSDN文库](https://download.csdn.net/download/qq_38161040/85232013?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-download-2~default~CTRLIST~Paid-1-85232013-blog-124214183.pc_relevant_landingrelevant&depth_1-utm_source=distribute.pc_relevant_t0.none-task-download-2~default~CTRLIST~Paid-1-85232013-blog-124214183.pc_relevant_landingrelevant)链接中下载对应包，并安装：

```python
conda install ale_py-0.7rc2-cp38-cp38-macosx_10_15_x86_64.whl
```

但是又出现报错：

```python
(tf_new) D:\tensorflow-new>conda install ale_py-0.7rc2-cp38-cp38-macosx_10_15_x86_64.whl
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ale_py-0.7rc2-cp38-cp38-macosx_10_15_x86_64.whl
```

打开Anaconda Prompt，激活环境并输入指令，ale-py安装问题成功解决：

```python
python -m pip install package
```



### 报错：

```python
Traceback (most recent call last):
  File "D:/tensorflow-new/main.py", line 74, in <module>
    tf.app.run()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "D:/tensorflow-new/main.py", line 57, in main
    env = GymEnvironment(config)
  File "D:\tensorflow-new\dqn\environment.py", line 68, in __init__
    super(GymEnvironment, self).__init__(config)
  File "D:\tensorflow-new\dqn\environment.py", line 8, in __init__
    self.env = gym.make(config.env_name)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\gym\envs\registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = cls(**_kwargs)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\ale_py\env\gym.py", line 155, in __init__
    self.seed()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\ale_py\env\gym.py", line 207, in seed
    f'We\'re Unable to find the game "{self._game}". Note: Gym no longer distributes ROMs. '
gym.error.Error: We're Unable to find the game "Breakout". Note: Gym no longer distributes ROMs. If you own a license to use the necessary ROMs for research purposes you can download them via `pip install gym[accept-rom-license]`. Otherwise, you should try importing "Breakout" via the command `ale-import-roms`. If you believe this is a mistake perhaps your copy of "Breakout" is unsupported. To check if this is the case try providing the environment variable `PYTHONWARNINGS=default::ImportWarning:ale_py.roms`. For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management

进程已结束，退出代码 1

```

解决方法：

版本回退，gym版本回退至0.19.0，Atari版本回退为0.2.6，执行如下两条命令：

```python
pip install gym==0.19.0
pip install atari_py==0.2.6
```

### 报错：

```python
Traceback (most recent call last):
  File "D:/tensorflow-new/main.py", line 81, in <module>
    tf.app.run()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "D:/tensorflow-new/main.py", line 73, in main
    agent = Agent(config, env, sess)
  File "D:\tensorflow-new\dqn\agent.py", line 24, in __init__
    self.memory = ReplayMemory(self.config, self.model_dir)
  File "D:\tensorflow-new\dqn\replay_memory.py", line 18, in __init__
    self.screens = np.empty((self.memory_size, config.screen_height, config.screen_width), dtype = np.float16)
numpy.core._exceptions.MemoryError: Unable to allocate 13.1 GiB for an array with shape (1000000, 84, 84) and data type float16
```

解决方法：增加虚拟内存



### 报错：

```python
Traceback (most recent call last):
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\gym\envs\classic_control\rendering.py", line 458, in __del__
    self.close()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\gym\envs\classic_control\rendering.py", line 454, in close
    self.window.close()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\pyglet\window\win32\__init__.py", line 332, in close
    super(Win32Window, self).close()
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\site-packages\pyglet\window\__init__.py", line 858, in close
    app.windows.remove(self)
  File "C:\Users\Yan xinyi\.conda\envs\tf_new\lib\_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: (<weakref at 0x000001A45A665318; to 'Win32Window' at 0x000001A45AC0B8C8>,)
```

解决方法：

在environment.py中添加

```python
class GridWorldEnv(gym.Env):
    def you_function():
        pass
 
    def close(self):
        if self.viewer:
            self.viewer.close()
            self.viewer = None
    # ...
```

在main.py中添加

```python
if __name__ == "__main__":
    env = GridWorldEnv()
    agent = Agent(env)
    # agent learning
    # after learning, then you can close the env
    agent.env.close() # 调用此行，关闭环境
```

但是报错仍然存在，由于不影响代码运行，遂摆烂
